Reorganize pre-commit hooks

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -12,17 +12,6 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-# Check compatibility with Zeitwerk
-echo "${green}[Zeitwerk Check][Info]: Checking Zeitwerk Check${NC}"
-
-bin/rails zeitwerk:check
-
-if [ $? -ne 0 ]; then
-  echo "${red}[Zeitwerk Check][Error]: Fix the issues and commit again${NC}"
-  exit 1
-fi
-
-
 # Code styling
 echo "${green}[Ruby Style][Info]: Checking Ruby Style${NC}"
 
@@ -57,6 +46,16 @@ fi
 rake unused_routes
 if [ $? -ne 0 ]; then
   echo "${red}[Unused Routes][Error]: Fix the issues and commit again${NC}"
+  exit 1
+fi
+
+# Check compatibility with Zeitwerk
+echo "${green}[Zeitwerk Check][Info]: Checking Zeitwerk Check${NC}"
+
+bin/rails zeitwerk:check
+
+if [ $? -ne 0 ]; then
+  echo "${red}[Zeitwerk Check][Error]: Fix the issues and commit again${NC}"
   exit 1
 fi
 
